### Alle Aufgaben
GET http://localhost:8080/api/tasks

###

### Aufgabe hinzufügen
POST http://localhost:8080/api/tasks
Content-Type: text/plain

Docker Compose mit PostgreSQL

###

### Alle Aufgaben erneut anzeigen
GET http://localhost:8080/api/tasks

###

### Aufgabe löschen
DELETE http://localhost:8080/api/tasks/1