### Alle DevOps-Aufgaben anzeigen (GET)
GET http://localhost:8080/api/tasks

### Neue DevOps-Aufgabe hinzufügen (POST)
POST http://localhost:8080/api/tasks
Content-Type: text/plain

Docker Compose konfigurieren

### DevOps-Aufgabe löschen (DELETE)
DELETE http://localhost:8080/api/tasks/0